app = "battlebox"
primary_region = "sjc"

[build]

[env]
  PORT = "8080"
  DB_PATH = "/data/db.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "battlebox_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
